ebs-ucdm: ucdm/ucdm.h File Reference
ucdm.h File Reference
Interface and usage of the Unified Configuration and Data Manager.
#include <platform/types.h>
#include <ds/avltree.h>
#include <stdint.h>
#include "config.h"
Data Structures
union UCDM_REGISTER_t
Macros
#define UCDM_EXST_KEEPALIVE_REQ 0x01
#define UCDM_EXST_TIMESYNC_REQ 0x02
UCDM Access Type Definitions for Register and Bit Read
#define UCDM_AT_READ_MASK 0x03
#define UCDM_AT_READ_NONE 0x00
#define UCDM_AT_READ_NORM 0x01
#define UCDM_AT_READ_PTR 0x02
#define UCDM_AT_READ_FUNC 0x03
UCDM Access Type Definitions for Bit Write
#define UCDM_AT_BITW_MASK 0x0C
#define UCDM_AT_BITW_RO 0x00
#define UCDM_AT_BITW_WE 0x04
#define UCDM_AT_BITW_HF 0x08
#define UCDM_AT_BITW_WE_HF 0x0C
UCDM Access Type Definitions for Register Write
#define UCDM_AT_REGW_MASK 0xF0
#define UCDM_AT_REGW_HF 0x80
#define UCDM_AT_REGW_VALIDATE 0x40
#define UCDM_AT_REGW_TYPE_MASK 0x30
#define UCDM_AT_REGW_TYPE_RO 0x00
#define UCDM_AT_REGW_TYPE_NORMAL 0x10
#define UCDM_AT_REGW_TYPE_PTR 0x20
#define UCDM_AT_REGW_TYPE_FUNC 0x30
Typedefs
typedef UCDM_REG_ADDR_TYPE ucdm_addr_t
typedef UCDM_BIT_ADDR_TYPE ucdm_addrb_t
typedef void(* ucdm_rw_handler_t) (ucdm_addr_t)
typedef void(* ucdm_bw_handler_t) (ucdm_addr_t, uint16_t)
typedef uint8_t ucdm_acctype_t
typedef union UCDM_REGISTER_t ucdm_register_t
Functions
UCDM Common Setup Functions
void ucdm_init (void)
Intitialize the UCDM subsystem.
UCDM Register Configuration Functions for Register Read
HAL_BASE_t ucdm_disable_regr (ucdm_addr_t addr)
Disable UCDM register register access on register.
HAL_BASE_t ucdm_enable_regr (ucdm_addr_t addr)
Enable UCDM register register access on register.
HAL_BASE_t ucdm_redirect_regr_ptr (ucdm_addr_t addr, uint16_t *target)
Configure UCDM register read access on this register to redirect to a pointer.
HAL_BASE_t ucdm_redirect_regr_func (ucdm_addr_t addr, uint16_t target(ucdm_addr_t))
Configure UCDM register read access on this register to redirect to a function pointer.
UCDM Register Configuration Functions for Bit Write
HAL_BASE_t ucdm_enable_bitw (ucdm_addr_t addr)
Enable UCDM bit write access on register.
HAL_BASE_t ucdm_disable_bitw (ucdm_addr_t addr)
Disable UCDM bit write access on register.
UCDM Register Configuration Functions for Register Write
HAL_BASE_t ucdm_disable_regw (ucdm_addr_t addr)
Disable UCDM register write access on a register.
HAL_BASE_t ucdm_enable_regw (ucdm_addr_t addr)
Enable UCDM register write access on a normal register.
HAL_BASE_t ucdm_redirect_regw_ptr (ucdm_addr_t addr, uint16_t *target)
Configure UCDM register write access on this register to redirect to a pointer.
HAL_BASE_t ucdm_redirect_regw_func (ucdm_addr_t addr, void target(ucdm_addr_t, uint16_t))
Configure UCDM register write access on this register to redirect to a function pointer.
UCDM Register Configuration Functions for Post-Write Handler Functions
HAL_BASE_t ucdm_install_regw_handler (ucdm_addr_t addr, avlt_node_t *rwh_node, ucdm_rw_handler_t handler)
Install a Register Write Handler for a UCDM register.
HAL_BASE_t ucdm_install_bitw_handler (ucdm_addr_t addr, avlt_node_t *bwh_node, ucdm_bw_handler_t handler)
Install a Bit Write Handler for a UCDM register.
UCDM Register Access Functions
HAL_BASE_t ucdm_set_register (ucdm_addr_t addr, uint16_t value)
Set the value of a UCDM register from protocol.
uint16_t ucdm_get_register (ucdm_addr_t addr)
Get the value of a UCDM register from protocol.
UCDM Bit Access Functions
static void ucdm_get_bit_addr (ucdm_addrb_t addrb, ucdm_addr_t *addr, uint16_t *mask)
Get the address of a UCDM bit from the identifier.
HAL_BASE_t ucdm_set_bit (ucdm_addrb_t addrb)
Set a UCDM bit from protocol.
HAL_BASE_t ucdm_clear_bit (ucdm_addrb_t addrb)
Clear a UCDM bit from protocol.
uint8_t ucdm_get_bit (ucdm_addrb_t addrb)
Get the value of a UCDM bit from protocol.
Variables
UCDM Configuration and Storage Containers
ucdm_register_t ucdm_register []
Actual storage for UCDM registers.
ucdm_acctype_t ucdm_acctype []
Actual storage for UCDM access type settings.
uint16_t ucdm_diagnostic_register
uint8_t ucdm_exception_status
Detailed Description
Interface and usage of the Unified Configuration and Data Manager.
This library provides the structures and related functions for implementing a unified configuration and data manager. This design is based on the MODBUS data model and is intended to interface seamlessly with MODBUS and derivative protocols.
UCDM Storage Model
The basic register type is uint16_t, and the number of configuration / data registers supported is configurable from within the application. The necessary variables and containers for this purpose need to be defined within the application. The tentatively recommended location is application/main.c.
See also
UCDM Configuration and Storage Containers
Each register can be configured to set allowed access type to one or more of the following :
Read-Only Register (modbus: Input Registers)
Read-Write Register (modbus: Holding Registers)
16 Read-Only Discrete Bits (modbus: Input Discrete)
16 Read-Write Discrete Bits (modbus: Coils)
Redirection
Though the UCDM library itself maintains storage, it is generally recommended to avoid using UCDM registers for storage and instead opting for one of the redirection methods. Redirection is configured through the register's access type configuration (ucdm_acctype). The following sections discuss the various available options.
Bit-level Access
Only basic support of bit read / write is implemented. Bit level access functions will only operate on normal UCDM registers, ie, registers which are stored directly in UCDM register storage. Specifically :
Bit read is allowed for all registers where read is allowed. However, it may not be appropriate for bits in UCDM registers with redirections in place. Bit reads for pointers will read the full register and return only the requested bit.
Bit write must be enabled if it is to be used, per register. Bit write should only be used on normal or pointer UCDM registers.
Bit reads and writes are not supported on registered configured for redirection using functions.
See also
UCDM Access Type Definitions for Bit Write
Register-level Access
Register read / write support is more thoroughly supported, allowing a variety of access types to be used. This implementation of the UCDM treats register read / write as the preferred (and primary) access method.
As in the case of bit read, register read is always allowed. However, register read can involve one of the following :
Normal register read, where content of the UCDM storage is returned.
Pointer register read, where content of the UCDM storage is treated as a pointer to where the data is actually stored (equal in size to the register),
Function Pointer register read, where content of the UCDM storage is treated as a pointer to a function which, when called with the register address, returns the data to be sent back (equal in size to the register). Such registers MUST be read only registers.
See also
UCDM Access Type Definitions for Register Read
Simlarly, register write allows a variety of write-types. Register write, though, like bit write, is not allowed by default. Register write must explicitly be enabled per register, irrespective of what write method is used. The following write methods are supported :
Normal register write, where content of the UCDM storage is written.
Pointer register write, where content of the UCDM storage is treated as a pointer to where the data should be written (equal in size to the register).
Function Pointer register write, where content of the UCDM storage is treated as a pointer to a function which must be called with the data to be written (equal in size to the register) and the register address. Such registers MUST be write only registers.
See also
UCDM Access Type Definitions for Register Write
Post-Write Handlers
For both register and bit write, UCDM can be configured to execute post-write handler functions after successful write. These handler functions must be set per-register, and will be called once per call to ucdm_set_register or ucdm_set_bit. In the case of register write, all types of writes can trigger the post-write handler function. Bit-write itself is not allowed for registers of the function write type, and post bit-write handlers are not applicable for such registers.
In general, bit write handlers are only called in response to a successful bit write operation. Register write handlers are called in response to a successful register write operation, as well as a successful bit write operation for which a bit write handler is not defined, but a register write handler is.
Application Notes
Register Access Types
Configuring the appropriate access type definitions should be done by the application code using the provided functions in this library's API. This configuration is expected to occur during initialization, and not during normal operation.
Register access type definitions provided can be used to configure the appropriate access types as needed, but should be avoided in favor of the configuration functions.
Note that in most cases, it will be necessary to set both the read and write operations on registers to the same type. This must be done by application code utilizing UCDM.
Post-Write Handlers
When using post-write handlers, remember that the application code using this handler must also provide the necessary data structures to contain and maintain the handler. The functions provided in this libary's API can help you do this, but they will not be called automatically here. Post-write handlers can also be pretty expensive, so it is preferable to resort to them only when redirection is insufficient.
Utilizing Function Pointers
When using function pointers, either with a function read / write type or as a post-write handler function, remember that these functions will be called from within the UCDM context. This means that the call stack is already pretty deep at this point. Further, communication protocols mounted atop the UCDM which are time-sensitive may not be able to wait for long running function calls to complete before sending a response. Keep these functions short and avoid deep calls. When necessary, just set a global flag and deal with it in the main loop.
The Device Map
The mapping between the register address and function, as well as the mapping between address and access types, are application specific, and should be defined in the application. The recommended location is application/devicemap.h
Internal Access
The application should internally just set the appropriate variables within the configuration and data buffer directly. The access exposed to the interface will always be more restrictive than that the application itself will require, and considerably more expensive. When they are being accessed via the UCDM, the functions provided by this library ensure the access is done correctly.
Casting to larger types
Users should not use UCDM internal storage with void pointers to simulate stores for larger types. This library does not guarantee that adjacent registers will be contiguous in memory. Specifically, on platforms where pointer sizes are larger than 16 bit, the actual data storage will become discontinuous. To overcome this problem, applications using UCDM to provide access to variables larger than 16-bit should use the pointer redirection functionality.
See also
ucdm.c
Definition in file ucdm.h.
Macro Definition Documentation
UCDM_AT_BITW_HF
#define UCDM_AT_BITW_HF 0x08
Bit Write, Enable Post-Write Handler Function (No effect without WE)
Definition at line 273 of file ucdm.h.
UCDM_AT_BITW_MASK
#define UCDM_AT_BITW_MASK 0x0C
Mask for UCDM Access Type, Bit Write
Definition at line 267 of file ucdm.h.
UCDM_AT_BITW_RO
#define UCDM_AT_BITW_RO 0x00
Bit Write, Not Allowed
Definition at line 269 of file ucdm.h.
UCDM_AT_BITW_WE
#define UCDM_AT_BITW_WE 0x04
Bit Write, Write Enabled
Definition at line 271 of file ucdm.h.
UCDM_AT_BITW_WE_HF
#define UCDM_AT_BITW_WE_HF 0x0C
Bit Write, Write Enabled, Enable Post-Write Handler Function
Definition at line 275 of file ucdm.h.
UCDM_AT_READ_FUNC
#define UCDM_AT_READ_FUNC 0x03
Register Read, Function (function ptr in ucdm storage)
Definition at line 259 of file ucdm.h.
UCDM_AT_READ_MASK
#define UCDM_AT_READ_MASK 0x03
Mask for UCDM Access Type, Register Read
Definition at line 251 of file ucdm.h.
UCDM_AT_READ_NONE
#define UCDM_AT_READ_NONE 0x00
Register Read, Not Allowed
Definition at line 253 of file ucdm.h.
UCDM_AT_READ_NORM
#define UCDM_AT_READ_NORM 0x01
Register Read, Normal (from ucdm storage)
Definition at line 255 of file ucdm.h.
UCDM_AT_READ_PTR
#define UCDM_AT_READ_PTR 0x02
Register Read, Pointer (ptr in ucdm storage)
Definition at line 257 of file ucdm.h.
UCDM_AT_REGW_HF
#define UCDM_AT_REGW_HF 0x80
Register Write, Enable Post-Write Handler Function (No effect without WE)
Definition at line 285 of file ucdm.h.
UCDM_AT_REGW_MASK
#define UCDM_AT_REGW_MASK 0xF0
Mask for UCDM Access Type, Register Write
Definition at line 283 of file ucdm.h.
UCDM_AT_REGW_TYPE_FUNC
#define UCDM_AT_REGW_TYPE_FUNC 0x30
Register Write, Write Enabled, Function (function ptr in ucdm storage)
Definition at line 297 of file ucdm.h.
UCDM_AT_REGW_TYPE_MASK
#define UCDM_AT_REGW_TYPE_MASK 0x30
Mask for UCDM Access Type, Register Write Type
Definition at line 289 of file ucdm.h.
UCDM_AT_REGW_TYPE_NORMAL
#define UCDM_AT_REGW_TYPE_NORMAL 0x10
Register Write, Write Enabled, Normal (to ucdm storage)
Definition at line 293 of file ucdm.h.
UCDM_AT_REGW_TYPE_PTR
#define UCDM_AT_REGW_TYPE_PTR 0x20
Register Write, Write Enabled, Pointer (ptr in ucdm storage)
Definition at line 295 of file ucdm.h.
UCDM_AT_REGW_TYPE_RO
#define UCDM_AT_REGW_TYPE_RO 0x00
Register Write, Not Allowed
Definition at line 291 of file ucdm.h.
UCDM_AT_REGW_VALIDATE
#define UCDM_AT_REGW_VALIDATE 0x40
Register Write, Enable Pre-Write Validation Function (Does not respect WE)
Definition at line 287 of file ucdm.h.
UCDM_EXST_KEEPALIVE_REQ
#define UCDM_EXST_KEEPALIVE_REQ 0x01
Definition at line 210 of file ucdm.h.
UCDM_EXST_TIMESYNC_REQ
#define UCDM_EXST_TIMESYNC_REQ 0x02
Definition at line 211 of file ucdm.h.
Typedef Documentation
ucdm_acctype_t
typedef uint8_t ucdm_acctype_t
Definition at line 219 of file ucdm.h.
ucdm_addr_t
typedef UCDM_REG_ADDR_TYPE ucdm_addr_t
Definition at line 213 of file ucdm.h.
ucdm_addrb_t
typedef UCDM_BIT_ADDR_TYPE ucdm_addrb_t
Definition at line 214 of file ucdm.h.
ucdm_bw_handler_t
typedef void(* ucdm_bw_handler_t) (ucdm_addr_t, uint16_t)
Definition at line 217 of file ucdm.h.
ucdm_register_t
typedef union UCDM_REGISTER_t ucdm_register_t
ucdm_rw_handler_t
typedef void(* ucdm_rw_handler_t) (ucdm_addr_t)
Definition at line 216 of file ucdm.h.
Function Documentation
ucdm_clear_bit()
HAL_BASE_t ucdm_clear_bit (ucdm_addrb_t addrb)
Clear a UCDM bit from protocol.
Parameters
addrb Address/identifier of the bit.
Returns
1 for bit cleared, 0 for access error.
Definition at line 343 of file ucdm.c.
References _ucdm_generic_wop_bit(), and _ucdm_wfunc_bitclear().
ucdm_disable_bitw()
HAL_BASE_t ucdm_disable_bitw (ucdm_addr_t addr)
Disable UCDM bit write access on register.
Parameters
addr Address/identifier of the register.
Definition at line 256 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
ucdm_disable_regr()
HAL_BASE_t ucdm_disable_regr (ucdm_addr_t addr)
Disable UCDM register register access on register.
Parameters
addr Address/identifier of the register.
Definition at line 95 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
Referenced by ucdm_redirect_regw_func().
ucdm_disable_regw()
HAL_BASE_t ucdm_disable_regw (ucdm_addr_t addr)
Disable UCDM register write access on a register.
The write type will be reset by this function.
Parameters
addr Address/identifier of the register.
Definition at line 165 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
Referenced by ucdm_redirect_regr_func().
ucdm_enable_bitw()
HAL_BASE_t ucdm_enable_bitw (ucdm_addr_t addr)
Enable UCDM bit write access on register.
Parameters
addr Address/identifier of the register.
Definition at line 247 of file ucdm.c.
References ucdm_acctype, UCDM_AT_BITW_WE, and UCDM_MAX_REGISTERS.
ucdm_enable_regr()
HAL_BASE_t ucdm_enable_regr (ucdm_addr_t addr)
Enable UCDM register register access on register.
Parameters
addr Address/identifier of the register.
Definition at line 104 of file ucdm.c.
References ucdm_acctype, UCDM_AT_READ_NORM, and UCDM_MAX_REGISTERS.
ucdm_enable_regw()
HAL_BASE_t ucdm_enable_regw (ucdm_addr_t addr)
Enable UCDM register write access on a normal register.
Parameters
addr Address/identifier of the register.
Definition at line 174 of file ucdm.c.
References ucdm_acctype, UCDM_AT_REGW_TYPE_NORMAL, and UCDM_MAX_REGISTERS.
ucdm_get_bit()
uint8_t ucdm_get_bit (ucdm_addrb_t addrb)
Get the value of a UCDM bit from protocol.
Parameters
addrb Address/identifier of the bit
Returns
Non-zero for bit is set, 0 for bit is cleared, 2 for address invalid
Definition at line 347 of file ucdm.c.
References ucdm_acctype, UCDM_AT_READ_FUNC, UCDM_AT_READ_MASK, UCDM_AT_READ_NONE, UCDM_AT_READ_NORM, UCDM_AT_READ_PTR, ucdm_get_bit_addr(), UCDM_MAX_BITS, and ucdm_register.
ucdm_get_bit_addr()
static void ucdm_get_bit_addr (ucdm_addrb_t addrb, ucdm_addr_t * addr, uint16_t * mask) inline static
Get the address of a UCDM bit from the identifier.
Parameters
addrb Identifier of the bit
addr Pointer to where the register address should be stored
mask Pointer to where the bitmask should be stored
Definition at line 491 of file ucdm.h.
Referenced by _ucdm_generic_wop_bit(), and ucdm_get_bit().
ucdm_get_register()
uint16_t ucdm_get_register (ucdm_addr_t addr)
Get the value of a UCDM register from protocol.
Parameters
addr Address/identifier of the register
Returns
Value of the register, or 0xFFFF if address is invalid.
Definition at line 134 of file ucdm.c.
References UCDM_REGISTER_t::data, UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_READ_FUNC, UCDM_AT_READ_MASK, UCDM_AT_READ_NONE, UCDM_AT_READ_NORM, UCDM_AT_READ_PTR, UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_init()
void ucdm_init (void)
Intitialize the UCDM subsystem.
Definition at line 82 of file ucdm.c.
References _ucdm_acctype_init(), _ucdm_handlers_init(), and _ucdm_registers_init().
ucdm_install_bitw_handler()
HAL_BASE_t ucdm_install_bitw_handler (ucdm_addr_t addr, avlt_node_t * bwh_node, ucdm_bw_handler_t handler)
Install a Bit Write Handler for a UCDM register.
Warning
This will overwrite any handler previously installed.
Parameters
addr Address/identifier of the register.
bwh_node Handler tree node container to use. This should be allocated and provided by the application.
handler Pointer to the handler function.
Definition at line 416 of file ucdm.c.
References _prepare_bitw_handler(), ucdm_acctype, UCDM_AT_BITW_HF, ucdm_bwht, and UCDM_MAX_REGISTERS.
ucdm_install_regw_handler()
HAL_BASE_t ucdm_install_regw_handler (ucdm_addr_t addr, avlt_node_t * rwh_node, ucdm_rw_handler_t handler)
Install a Register Write Handler for a UCDM register.
Warning
This will overwrite any handler previously installed.
Parameters
addr Address/identifier of the register.
rwh_node Handler tree node container to use. This should be allocated and provided by the application.
handler Pointer to the handler function.
Definition at line 393 of file ucdm.c.
References _prepare_regw_handler(), ucdm_acctype, UCDM_AT_REGW_HF, UCDM_MAX_REGISTERS, and ucdm_rwht.
ucdm_redirect_regr_func()
HAL_BASE_t ucdm_redirect_regr_func (ucdm_addr_t addr, uint16_t targetucdm_addr_t)
Configure UCDM register read access on this register to redirect to a function pointer.
This disables writes to this register if enabled. Note, however, that applications could enable write to this register after calling this function. While there is no good reason to ever do so, we do nothing to prevent this from happening.
Parameters
addr Address/identifier of the register.
target Pointer to the funcition where the reads should be redirected to.
Definition at line 123 of file ucdm.c.
References UCDM_REGISTER_t::rfunc, ucdm_acctype, UCDM_AT_READ_FUNC, ucdm_disable_regw(), UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_redirect_regr_ptr()
HAL_BASE_t ucdm_redirect_regr_ptr (ucdm_addr_t addr, uint16_t * target)
Configure UCDM register read access on this register to redirect to a pointer.
Note that in most instances, applications should also call ucdm_redirect_regw_ptr.
Parameters
addr Address/identifier of the register.
target Pointer to the address where the reads should be redirected to.
Definition at line 113 of file ucdm.c.
References UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_READ_PTR, UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_redirect_regw_func()
HAL_BASE_t ucdm_redirect_regw_func (ucdm_addr_t addr, void targetucdm_addr_t, uint16_t)
Configure UCDM register write access on this register to redirect to a function pointer.
Write enable is also set implicitly.
This disables reads from this register if enabled. Note, however, that applications could enable read on this register after calling this function. While there is no good reason to ever do so, we do nothing to prevent this from happening. .
Parameters
addr Address/identifier of the register.
target Pointer to the funcition where the writes should be redirected to.
Definition at line 193 of file ucdm.c.
References ucdm_acctype, UCDM_AT_REGW_TYPE_FUNC, ucdm_disable_regr(), UCDM_MAX_REGISTERS, ucdm_register, and UCDM_REGISTER_t::wfunc.
ucdm_redirect_regw_ptr()
HAL_BASE_t ucdm_redirect_regw_ptr (ucdm_addr_t addr, uint16_t * target)
Configure UCDM register write access on this register to redirect to a pointer.
Write enable is also set implicitly. Note that in most instances, applications should also call ucdm_redirect_regr_ptr.
Parameters
addr Address/identifier of the register.
target Pointer to the address where the writes should be redirected to.
Definition at line 183 of file ucdm.c.
References UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_REGW_TYPE_PTR, UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_set_bit()
HAL_BASE_t ucdm_set_bit (ucdm_addrb_t addrb)
Set a UCDM bit from protocol.
Parameters
addrb Address/identifier of the bit
Returns
1 for bit set, 0 for access error.
Definition at line 339 of file ucdm.c.
References _ucdm_generic_wop_bit(), and _ucdm_wfunc_bitset().
ucdm_set_register()
HAL_BASE_t ucdm_set_register (ucdm_addr_t addr, uint16_t value)
Set the value of a UCDM register from protocol.
Parameters
addr Address/identifier of the register
value The value to be set
Returns
0 for register set, 1 for register out of range, 2 for access error.
Definition at line 205 of file ucdm.c.
References UCDM_REGISTER_t::data, UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_REGW_HF, UCDM_AT_REGW_TYPE_FUNC, UCDM_AT_REGW_TYPE_MASK, UCDM_AT_REGW_TYPE_NORMAL, UCDM_AT_REGW_TYPE_PTR, UCDM_AT_REGW_TYPE_RO, UCDM_MAX_REGISTERS, ucdm_register, ucdm_rwht, and UCDM_REGISTER_t::wfunc.
Variable Documentation
ucdm_acctype
ucdm_acctype_t ucdm_acctype[] extern
Actual storage for UCDM access type settings.
Definition at line 47 of file ucdm.c.
Referenced by _ucdm_acctype_init(), _ucdm_exec_bit_handler(), _ucdm_generic_wop_bit(), ucdm_disable_bitw(), ucdm_disable_regr(), ucdm_disable_regw(), ucdm_enable_bitw(), ucdm_enable_regr(), ucdm_enable_regw(), ucdm_get_bit(), ucdm_get_register(), ucdm_install_bitw_handler(), ucdm_install_regw_handler(), ucdm_redirect_regr_func(), ucdm_redirect_regr_ptr(), ucdm_redirect_regw_func(), ucdm_redirect_regw_ptr(), and ucdm_set_register().
ucdm_diagnostic_register
uint16_t ucdm_diagnostic_register extern
Definition at line 38 of file ucdm.c.
ucdm_exception_status
uint8_t ucdm_exception_status extern
Definition at line 39 of file ucdm.c.
ucdm_register
ucdm_register_t ucdm_register[] extern
Actual storage for UCDM registers.
Definition at line 46 of file ucdm.c.
Referenced by _ucdm_generic_wop_bit(), _ucdm_registers_init(), ucdm_get_bit(), ucdm_get_register(), ucdm_redirect_regr_func(), ucdm_redirect_regr_ptr(), ucdm_redirect_regw_func(), ucdm_redirect_regw_ptr(), and ucdm_set_register().