ebs-ucdm: ucdm/ucdm.c File Reference
ucdm.c File Reference
Implementation the Unified Configuration and Data Manager.
#include <string.h>
#include "ucdm.h"
#include "span.h"
#include "descriptor.h"
Functions
static void _ucdm_registers_init (void)
static void _ucdm_acctype_init (void)
static void _ucdm_handlers_init (void)
void ucdm_init (void)
Intitialize the UCDM subsystem.
HAL_BASE_t ucdm_disable_regr (ucdm_addr_t addr)
Disable UCDM register register access on register.
HAL_BASE_t ucdm_enable_regr (ucdm_addr_t addr)
Enable UCDM register register access on register.
HAL_BASE_t ucdm_redirect_regr_ptr (ucdm_addr_t addr, uint16_t *target)
Configure UCDM register read access on this register to redirect to a pointer.
HAL_BASE_t ucdm_redirect_regr_func (ucdm_addr_t addr, uint16_t target(ucdm_addr_t))
Configure UCDM register read access on this register to redirect to a function pointer.
uint16_t ucdm_get_register (ucdm_addr_t addr)
Get the value of a UCDM register from protocol.
HAL_BASE_t ucdm_disable_regw (ucdm_addr_t addr)
Disable UCDM register write access on a register.
HAL_BASE_t ucdm_enable_regw (ucdm_addr_t addr)
Enable UCDM register write access on a normal register.
HAL_BASE_t ucdm_redirect_regw_ptr (ucdm_addr_t addr, uint16_t *target)
Configure UCDM register write access on this register to redirect to a pointer.
HAL_BASE_t ucdm_redirect_regw_func (ucdm_addr_t addr, void target(ucdm_addr_t, uint16_t))
Configure UCDM register write access on this register to redirect to a function pointer.
HAL_BASE_t ucdm_set_register (ucdm_addr_t addr, uint16_t value)
Set the value of a UCDM register from protocol.
HAL_BASE_t ucdm_enable_bitw (ucdm_addr_t addr)
Enable UCDM bit write access on register.
HAL_BASE_t ucdm_disable_bitw (ucdm_addr_t addr)
Disable UCDM bit write access on register.
static void _ucdm_wfunc_bitset (uint16_t *target, uint16_t mask)
static void _ucdm_wfunc_bitclear (uint16_t *target, uint16_t mask)
static uint8_t _ucdm_generic_wop_bit (ucdm_addrb_t addrb, void wfunc(uint16_t *, uint16_t))
static void _ucdm_exec_bit_handler (ucdm_addr_t addr, uint16_t mask)
HAL_BASE_t ucdm_set_bit (ucdm_addrb_t addrb)
Set a UCDM bit from protocol.
HAL_BASE_t ucdm_clear_bit (ucdm_addrb_t addrb)
Clear a UCDM bit from protocol.
uint8_t ucdm_get_bit (ucdm_addrb_t addrb)
Get the value of a UCDM bit from protocol.
static void _prepare_regw_handler (avlt_node_t *node, ucdm_addr_t addr, ucdm_rw_handler_t handler)
HAL_BASE_t ucdm_install_regw_handler (ucdm_addr_t addr, avlt_node_t *rwh_node, ucdm_rw_handler_t handler)
Install a Register Write Handler for a UCDM register.
static void _prepare_bitw_handler (avlt_node_t *node, ucdm_addr_t addr, ucdm_bw_handler_t handler)
HAL_BASE_t ucdm_install_bitw_handler (ucdm_addr_t addr, avlt_node_t *bwh_node, ucdm_bw_handler_t handler)
Install a Bit Write Handler for a UCDM register.
Variables
uint16_t ucdm_diagnostic_register
uint8_t ucdm_exception_status
avlt_t ucdm_rwht
avlt_t ucdm_bwht
ucdm_register_t ucdm_register [UCDM_MAX_REGISTERS]
Actual storage for UCDM registers.
ucdm_acctype_t ucdm_acctype [UCDM_MAX_REGISTERS]
Actual storage for UCDM access type settings.
Detailed Description
Implementation the Unified Configuration and Data Manager.
See ucdm.h for usage documentation. Implementation documentation should be added to this file as some point.
See also
ucdm.h
Definition in file ucdm.c.
Function Documentation
_prepare_bitw_handler()
static void _prepare_bitw_handler (avlt_node_t * node, ucdm_addr_t addr, ucdm_bw_handler_t handler) static
Definition at line 409 of file ucdm.c.
Referenced by ucdm_install_bitw_handler().
_prepare_regw_handler()
static void _prepare_regw_handler (avlt_node_t * node, ucdm_addr_t addr, ucdm_rw_handler_t handler) static
Definition at line 386 of file ucdm.c.
Referenced by ucdm_install_regw_handler().
_ucdm_acctype_init()
static void _ucdm_acctype_init (void) inline static
Definition at line 57 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
Referenced by ucdm_init().
_ucdm_exec_bit_handler()
static void _ucdm_exec_bit_handler (ucdm_addr_t addr, uint16_t mask) static
Definition at line 273 of file ucdm.c.
References ucdm_acctype, UCDM_AT_BITW_HF, UCDM_AT_REGW_HF, ucdm_bwht, and ucdm_rwht.
Referenced by _ucdm_generic_wop_bit().
_ucdm_generic_wop_bit()
static uint8_t _ucdm_generic_wop_bit (ucdm_addrb_t addrb, void wfuncuint16_t *, uint16_t) static
Definition at line 302 of file ucdm.c.
References _ucdm_exec_bit_handler(), ucdm_acctype, UCDM_AT_BITW_WE, UCDM_AT_READ_FUNC, UCDM_AT_READ_NONE, UCDM_AT_REGW_TYPE_MASK, UCDM_AT_REGW_TYPE_NORMAL, UCDM_AT_REGW_TYPE_PTR, ucdm_get_bit_addr(), UCDM_MAX_BITS, and ucdm_register.
Referenced by ucdm_clear_bit(), and ucdm_set_bit().
_ucdm_handlers_init()
static void _ucdm_handlers_init (void) inline static
Definition at line 75 of file ucdm.c.
References ucdm_bwht, and ucdm_rwht.
Referenced by ucdm_init().
_ucdm_registers_init()
static void _ucdm_registers_init (void) inline static
Definition at line 53 of file ucdm.c.
References UCDM_MAX_REGISTERS, and ucdm_register.
Referenced by ucdm_init().
_ucdm_wfunc_bitclear()
static void _ucdm_wfunc_bitclear (uint16_t * target, uint16_t mask) inline static
Definition at line 297 of file ucdm.c.
Referenced by ucdm_clear_bit().
_ucdm_wfunc_bitset()
static void _ucdm_wfunc_bitset (uint16_t * target, uint16_t mask) inline static
Definition at line 292 of file ucdm.c.
Referenced by ucdm_set_bit().
ucdm_clear_bit()
HAL_BASE_t ucdm_clear_bit (ucdm_addrb_t addrb)
Clear a UCDM bit from protocol.
Parameters
addrb Address/identifier of the bit.
Returns
1 for bit cleared, 0 for access error.
Definition at line 343 of file ucdm.c.
References _ucdm_generic_wop_bit(), and _ucdm_wfunc_bitclear().
ucdm_disable_bitw()
HAL_BASE_t ucdm_disable_bitw (ucdm_addr_t addr)
Disable UCDM bit write access on register.
Parameters
addr Address/identifier of the register.
Definition at line 256 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
ucdm_disable_regr()
HAL_BASE_t ucdm_disable_regr (ucdm_addr_t addr)
Disable UCDM register register access on register.
Parameters
addr Address/identifier of the register.
Definition at line 95 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
Referenced by ucdm_redirect_regw_func().
ucdm_disable_regw()
HAL_BASE_t ucdm_disable_regw (ucdm_addr_t addr)
Disable UCDM register write access on a register.
The write type will be reset by this function.
Parameters
addr Address/identifier of the register.
Definition at line 165 of file ucdm.c.
References ucdm_acctype, and UCDM_MAX_REGISTERS.
Referenced by ucdm_redirect_regr_func().
ucdm_enable_bitw()
HAL_BASE_t ucdm_enable_bitw (ucdm_addr_t addr)
Enable UCDM bit write access on register.
Parameters
addr Address/identifier of the register.
Definition at line 247 of file ucdm.c.
References ucdm_acctype, UCDM_AT_BITW_WE, and UCDM_MAX_REGISTERS.
ucdm_enable_regr()
HAL_BASE_t ucdm_enable_regr (ucdm_addr_t addr)
Enable UCDM register register access on register.
Parameters
addr Address/identifier of the register.
Definition at line 104 of file ucdm.c.
References ucdm_acctype, UCDM_AT_READ_NORM, and UCDM_MAX_REGISTERS.
ucdm_enable_regw()
HAL_BASE_t ucdm_enable_regw (ucdm_addr_t addr)
Enable UCDM register write access on a normal register.
Parameters
addr Address/identifier of the register.
Definition at line 174 of file ucdm.c.
References ucdm_acctype, UCDM_AT_REGW_TYPE_NORMAL, and UCDM_MAX_REGISTERS.
ucdm_get_bit()
uint8_t ucdm_get_bit (ucdm_addrb_t addrb)
Get the value of a UCDM bit from protocol.
Parameters
addrb Address/identifier of the bit
Returns
Non-zero for bit is set, 0 for bit is cleared, 2 for address invalid
Definition at line 347 of file ucdm.c.
References ucdm_acctype, UCDM_AT_READ_FUNC, UCDM_AT_READ_MASK, UCDM_AT_READ_NONE, UCDM_AT_READ_NORM, UCDM_AT_READ_PTR, ucdm_get_bit_addr(), UCDM_MAX_BITS, and ucdm_register.
ucdm_get_register()
uint16_t ucdm_get_register (ucdm_addr_t addr)
Get the value of a UCDM register from protocol.
Parameters
addr Address/identifier of the register
Returns
Value of the register, or 0xFFFF if address is invalid.
Definition at line 134 of file ucdm.c.
References UCDM_REGISTER_t::data, UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_READ_FUNC, UCDM_AT_READ_MASK, UCDM_AT_READ_NONE, UCDM_AT_READ_NORM, UCDM_AT_READ_PTR, UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_init()
void ucdm_init (void)
Intitialize the UCDM subsystem.
Definition at line 82 of file ucdm.c.
References _ucdm_acctype_init(), _ucdm_handlers_init(), and _ucdm_registers_init().
ucdm_install_bitw_handler()
HAL_BASE_t ucdm_install_bitw_handler (ucdm_addr_t addr, avlt_node_t * bwh_node, ucdm_bw_handler_t handler)
Install a Bit Write Handler for a UCDM register.
Warning
This will overwrite any handler previously installed.
Parameters
addr Address/identifier of the register.
bwh_node Handler tree node container to use. This should be allocated and provided by the application.
handler Pointer to the handler function.
Definition at line 416 of file ucdm.c.
References _prepare_bitw_handler(), ucdm_acctype, UCDM_AT_BITW_HF, ucdm_bwht, and UCDM_MAX_REGISTERS.
ucdm_install_regw_handler()
HAL_BASE_t ucdm_install_regw_handler (ucdm_addr_t addr, avlt_node_t * rwh_node, ucdm_rw_handler_t handler)
Install a Register Write Handler for a UCDM register.
Warning
This will overwrite any handler previously installed.
Parameters
addr Address/identifier of the register.
rwh_node Handler tree node container to use. This should be allocated and provided by the application.
handler Pointer to the handler function.
Definition at line 393 of file ucdm.c.
References _prepare_regw_handler(), ucdm_acctype, UCDM_AT_REGW_HF, UCDM_MAX_REGISTERS, and ucdm_rwht.
ucdm_redirect_regr_func()
HAL_BASE_t ucdm_redirect_regr_func (ucdm_addr_t addr, uint16_t targetucdm_addr_t)
Configure UCDM register read access on this register to redirect to a function pointer.
This disables writes to this register if enabled. Note, however, that applications could enable write to this register after calling this function. While there is no good reason to ever do so, we do nothing to prevent this from happening.
Parameters
addr Address/identifier of the register.
target Pointer to the funcition where the reads should be redirected to.
Definition at line 123 of file ucdm.c.
References UCDM_REGISTER_t::rfunc, ucdm_acctype, UCDM_AT_READ_FUNC, ucdm_disable_regw(), UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_redirect_regr_ptr()
HAL_BASE_t ucdm_redirect_regr_ptr (ucdm_addr_t addr, uint16_t * target)
Configure UCDM register read access on this register to redirect to a pointer.
Note that in most instances, applications should also call ucdm_redirect_regw_ptr.
Parameters
addr Address/identifier of the register.
target Pointer to the address where the reads should be redirected to.
Definition at line 113 of file ucdm.c.
References UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_READ_PTR, UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_redirect_regw_func()
HAL_BASE_t ucdm_redirect_regw_func (ucdm_addr_t addr, void targetucdm_addr_t, uint16_t)
Configure UCDM register write access on this register to redirect to a function pointer.
Write enable is also set implicitly.
This disables reads from this register if enabled. Note, however, that applications could enable read on this register after calling this function. While there is no good reason to ever do so, we do nothing to prevent this from happening. .
Parameters
addr Address/identifier of the register.
target Pointer to the funcition where the writes should be redirected to.
Definition at line 193 of file ucdm.c.
References ucdm_acctype, UCDM_AT_REGW_TYPE_FUNC, ucdm_disable_regr(), UCDM_MAX_REGISTERS, ucdm_register, and UCDM_REGISTER_t::wfunc.
ucdm_redirect_regw_ptr()
HAL_BASE_t ucdm_redirect_regw_ptr (ucdm_addr_t addr, uint16_t * target)
Configure UCDM register write access on this register to redirect to a pointer.
Write enable is also set implicitly. Note that in most instances, applications should also call ucdm_redirect_regr_ptr.
Parameters
addr Address/identifier of the register.
target Pointer to the address where the writes should be redirected to.
Definition at line 183 of file ucdm.c.
References UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_REGW_TYPE_PTR, UCDM_MAX_REGISTERS, and ucdm_register.
ucdm_set_bit()
HAL_BASE_t ucdm_set_bit (ucdm_addrb_t addrb)
Set a UCDM bit from protocol.
Parameters
addrb Address/identifier of the bit
Returns
1 for bit set, 0 for access error.
Definition at line 339 of file ucdm.c.
References _ucdm_generic_wop_bit(), and _ucdm_wfunc_bitset().
ucdm_set_register()
HAL_BASE_t ucdm_set_register (ucdm_addr_t addr, uint16_t value)
Set the value of a UCDM register from protocol.
Parameters
addr Address/identifier of the register
value The value to be set
Returns
0 for register set, 1 for register out of range, 2 for access error.
Definition at line 205 of file ucdm.c.
References UCDM_REGISTER_t::data, UCDM_REGISTER_t::ptr, ucdm_acctype, UCDM_AT_REGW_HF, UCDM_AT_REGW_TYPE_FUNC, UCDM_AT_REGW_TYPE_MASK, UCDM_AT_REGW_TYPE_NORMAL, UCDM_AT_REGW_TYPE_PTR, UCDM_AT_REGW_TYPE_RO, UCDM_MAX_REGISTERS, ucdm_register, ucdm_rwht, and UCDM_REGISTER_t::wfunc.
Variable Documentation
ucdm_acctype
ucdm_acctype_t ucdm_acctype[UCDM_MAX_REGISTERS]
Actual storage for UCDM access type settings.
Definition at line 47 of file ucdm.c.
Referenced by _ucdm_acctype_init(), _ucdm_exec_bit_handler(), _ucdm_generic_wop_bit(), ucdm_disable_bitw(), ucdm_disable_regr(), ucdm_disable_regw(), ucdm_enable_bitw(), ucdm_enable_regr(), ucdm_enable_regw(), ucdm_get_bit(), ucdm_get_register(), ucdm_install_bitw_handler(), ucdm_install_regw_handler(), ucdm_redirect_regr_func(), ucdm_redirect_regr_ptr(), ucdm_redirect_regw_func(), ucdm_redirect_regw_ptr(), and ucdm_set_register().
ucdm_bwht
avlt_t ucdm_bwht
Definition at line 43 of file ucdm.c.
Referenced by _ucdm_exec_bit_handler(), _ucdm_handlers_init(), and ucdm_install_bitw_handler().
ucdm_diagnostic_register
uint16_t ucdm_diagnostic_register
Definition at line 38 of file ucdm.c.
ucdm_exception_status
uint8_t ucdm_exception_status
Definition at line 39 of file ucdm.c.
ucdm_register
ucdm_register_t ucdm_register[UCDM_MAX_REGISTERS]
Actual storage for UCDM registers.
Definition at line 46 of file ucdm.c.
Referenced by _ucdm_generic_wop_bit(), _ucdm_registers_init(), ucdm_get_bit(), ucdm_get_register(), ucdm_redirect_regr_func(), ucdm_redirect_regr_ptr(), ucdm_redirect_regw_func(), ucdm_redirect_regw_ptr(), and ucdm_set_register().
ucdm_rwht
avlt_t ucdm_rwht
Definition at line 42 of file ucdm.c.
Referenced by _ucdm_exec_bit_handler(), _ucdm_handlers_init(), ucdm_install_regw_handler(), and ucdm_set_register().