ebs-ucdm: UCDM_REGISTER_t Union Reference
UCDM_REGISTER_t Union Reference
#include <ucdm/ucdm.h>
Data Fields
uint16_t data
uint16_t * ptr
uint16_t(* rfunc)(ucdm_addr_t)
void(* wfunc)(ucdm_addr_t, uint16_t)
Detailed Description
Definition at line 221 of file ucdm.h.
Field Documentation
data
uint16_t data
Definition at line 222 of file ucdm.h.
Referenced by ucdm_get_register(), and ucdm_set_register().
ptr
uint16_t* ptr
Definition at line 223 of file ucdm.h.
Referenced by ucdm_get_register(), ucdm_redirect_regr_ptr(), ucdm_redirect_regw_ptr(), and ucdm_set_register().
rfunc
uint16_t(* rfunc) (ucdm_addr_t)
Definition at line 224 of file ucdm.h.
Referenced by ucdm_redirect_regr_func().
wfunc
void(* wfunc) (ucdm_addr_t, uint16_t)
Definition at line 225 of file ucdm.h.
Referenced by ucdm_redirect_regw_func(), and ucdm_set_register().
The documentation for this union was generated from the following file:
ucdm/ucdm.h